### ISSUE TITLE
NullPointerException on sbt ~run

### ISSUE THREAD

**Issue by crawlem** [commercetools/commercetools-sunrise-java-starter#60] opened 2019-02-04 21:37 UTC
I've cloned the project, setup conf/dev.conf with my project & client info and run sbt ~run.
MacOs 10.13, sbt 1.2.8 (installed view brew), Java 10.0.2-adoptopenjdk

    iMac:commercetools-sunrise-java-starter crawleym$ sbt ~run
    [info] Loading project definition from /Users/crawleym/Desktop/commercetools-sunrise-java-starter/project
    java.lang.NullPointerException
    	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1769)
    	at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
    	at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
    	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1130)
    	at java.base/java.util.regex.Pattern.split(Pattern.java:1249)
    	at java.base/java.util.regex.Pattern.split(Pattern.java:1322)
    	at sbt.IO$.pathSplit(IO.scala:797)
    	at sbt.IO$.parseClasspath(IO.scala:912)
    	at sbt.compiler.CompilerArguments.extClasspath(CompilerArguments.scala:66)
    	at sbt.compiler.MixedAnalyzingCompiler$.withBootclasspath(MixedAnalyzingCompiler.scala:188)
    	at sbt.compiler.MixedAnalyzingCompiler$.searchClasspathAndLookup(MixedAnalyzingCompiler.scala:166)
    	at sbt.compiler.MixedAnalyzingCompiler$.apply(MixedAnalyzingCompiler.scala:176)
    	at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
    	at sbt.Compiler$.compile(Compiler.scala:152)
    	at sbt.Compiler$.compile(Compiler.scala:138)
    	at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:860)
    	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:851)
    	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:849)
    	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    	at sbt.std.Transform$$anon$4.work(System.scala:63)
    	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    	at sbt.Execute.work(Execute.scala:237)
    	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
    	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    	at java.base/java.lang.Thread.run(Thread.java:844)
    [error] (compile:compileIncremental) java.lang.NullPointerException
    Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

**Comment by lauraluiz** [comment] 2019-02-05 09:45
It seems to be related to your SBT version: https://github.com/sbt/sbt/issues/4259
Could you please try the fix explained in there and let me know if it worked?

**Comment by flxlisboa** [comment] 2019-02-07 17:07
I can confirm that the suggestion above works.
In a nutshell: 

- Installed sbt 0.3.18 (`brew install sbt@0.13.18`)
- Changed sbt.version to 0.13.18 in project/build.properties

**Comment by crawlem** [comment] 2019-02-07 20:03
Bingo thank you!

**Comment by lauraluiz** [comment] 2019-02-08 15:25
Good to hear it worked :)
I'll close the issue then.

**Closed as completed by lauraluiz** 2019-02-08 15:25 UTC
